// Generated by assets/campaign/portraits/bake.mjs: each Mentat's name, the point his head turns about, and where
// each baked layer sits in the portrait's 400 x 500 frame ([x, y, width, height] in SVG units). Bake again; do not
// edit by hand.
export const PORTRAITS = {
  atreides: {
    name: 'Cyril', pivot: [208, 318],
    layers: { back: [0, 0, 400, 500], body: [0, 209.58, 400, 290.42], head: [113.75, 49.17, 181.25, 242.92], lids: [145, 158.75, 122.5, 42.5] },
  },
  harkonnen: {
    name: 'Radnor', pivot: [210, 360],
    layers: { back: [0, 0, 400, 500], body: [0, 269.17, 400, 230.83], head: [97.92, 62.92, 200.42, 274.17], lids: [142.08, 175.83, 135, 41.67] },
  },
  ordos: {
    name: 'Ammon', pivot: [208, 330],
    layers: { back: [0, 0, 400, 500], body: [0, 250.83, 400, 249.17], head: [122.08, 54.17, 152.08, 250.42], lids: [147.92, 158.75, 115.42, 39.58] },
  },
};
