// Generated by assets/campaign/portraits/bake.mjs: each Mentat's name, the point his head turns about, where each
// baked layer sits in the portrait's 400 x 500 frame, and where the face's moving parts fall in it (the mouth, the
// brows and the eyes with their lids, left and right as seen), all [x, y, width, height] in frame units. Bake
// again; do not edit by hand.
export const PORTRAITS = {
  atreides: {
    name: 'Cyril', pivot: [200, 311],
    layers: { back: [0, 0, 400, 500], body: [0, 185, 400, 315], head: [128.33, 50.83, 152.08, 258.75], lids: [174.17, 147.5, 98.75, 42.08] },
    features: { mouth: [194.6, 215.2, 50.3, 30.9], browL: [174.4, 140.9, 48, 21.1], browR: [233.1, 145.3, 36.9, 18.1], eyeL: [181.5, 155.4, 30.4, 23.7], eyeR: [236.9, 158.4, 29.8, 23.4] },
  },
  harkonnen: {
    name: 'Radnor', pivot: [200, 310],
    layers: { back: [0, 0, 400, 500], body: [0, 157.5, 400, 342.5], head: [114.58, 24.58, 170.83, 303.33], lids: [162.5, 135, 117.92, 48.75] },
    features: { mouth: [180.2, 216.2, 65, 34.9], browL: [163.7, 127.9, 56.2, 31.6], browR: [231.3, 136.2, 47, 24.4], eyeL: [170.5, 143.3, 36.2, 27.2], eyeR: [236.9, 148.3, 35.7, 27] },
  },
  ordos: {
    name: 'Ammon', pivot: [200, 315],
    layers: { back: [0, 0, 400, 500], body: [0, 181.25, 400, 318.75], head: [129.17, 40.42, 143.33, 295], lids: [162.92, 125.42, 105, 42.08] },
    features: { mouth: [193.8, 201.5, 50.3, 25.3], browL: [160.7, 120.3, 49.4, 18.6], browR: [222.7, 119.7, 42.1, 16.2], eyeL: [170.6, 135.6, 31.3, 23.9], eyeR: [229.4, 133.6, 30.9, 23.7] },
  },
};
