// Announcer voices (spec §6 Announcer; research audio-ui-controls.md §A.1). The player's house speaks its
// news, the answers to its own clicks and its alerts in pre-rendered lines (assets/voice, generated by
// scripts/voices/generate.py: one deep announcer shared by every house, as on the Mega Drive, the default;
// an announcer per Great House, as on the PC, under Options → Announcer "Each house"; and a voice for each
// kind of unit answering its selection and orders, src/data/unit-voices.js). One line at a time: a small priority queue puts alerts
// before routine news, drops what went stale while it waited and what was said moments ago. Lines are
// decoded after the first click has opened the audio and play on their own gain into the sound engine's
// master bus, so the master volume and the M mute apply to them too. The message bar keeps every text.
// Without Web Audio, the manifest or a decodable file the game simply stays quiet; nothing here throws.
// With "Use the original sounds" on (Options → Original Game Files, spec §6), the lines the original spoke
// come from the player's own Dune II clips instead, strung together from its word clips as it did
// (src/formats/dune2-sounds.js); any line they cannot make keeps its pre-rendered voice.
import { HOUSES } from '../data/houses.js';
import { ORIGINAL_LINES, RATE, resolveLine, voiceLine } from '../formats/dune2-sounds.js';
import { parseUnitLine } from '../data/unit-voices.js';
import { DEFAULTS, loadSettings } from '../core/settings.js';
import { readParams } from '../core/params.js';

export const VOICE_BASE = new URL('../../assets/voice/', import.meta.url).href;
export const VOICE_LEVEL = 0.85;  // lines are mastered to -16 LUFS; at the default Voices 80 % they sit ~5 dB over one effect (-21…-32 LUFS)
export const GAP = 0.18;          // seconds of quiet between two lines
export const LEAD = 0.15;         // an announcement waits this long so the interface's chirp comes first; acknowledgements do not
export const ERROR_LEAD = 0.27;   // a refusal waits out the error buzz (0.31 s; speech starts ≥0.05 s into a line), not talk over it

/** How urgent a class of line is, how long it may wait for its turn and how soon it may repeat (seconds). */
export const CLASSES = {
  critical: { priority: 4, maxAge: 12, cooldown: 0 },     // the battle's end, a missile on its way
  alert: { priority: 3, maxAge: 5, cooldown: 4 },         // danger: attacks, sightings, buildings lost
  feedback: { priority: 2, maxAge: 1.5, cooldown: 0.8 },  // the answer to the player's own click: now or never
  news: { priority: 1, maxAge: 6, cooldown: 2 },          // things done: construction complete, unit ready
  ack: { priority: 0, maxAge: 0.7, cooldown: 1.4 },       // the old shared replies, kept for a unit line that cannot be had
  select: { priority: 0, maxAge: 0.7, cooldown: 0.8 },    // a unit answering being selected, if nothing else is said
  order: { priority: 0, maxAge: 1.2, cooldown: 1.2, cuts: 'select' },   // … and its orders: that answer takes the selection's place, even mid-word, as the original's replies did
};
const AT_ONCE = new Set(['ack', 'select', 'order']);   // units answer at once: no interface sound to wait for

// Line groups (the id before any '.') → [class, cooldown override]. The old shared replies share the 'ack' group.
const GROUPS = {
  missionAccomplished: ['critical'], missionFailed: ['critical'], draw: ['critical'], missileApproaching: ['critical'],
  baseAttack: ['alert'], harvesterAttack: ['alert'], approaching: ['alert', 20], wormsign: ['alert', 30], structureLost: ['alert', 2],
  lostToCapture: ['alert'], lowPower: ['alert', 10],
  building: ['feedback'], training: ['feedback'], upgrading: ['feedback'], onHold: ['feedback'], cancelled: ['feedback'],
  unableToComply: ['feedback'], insufficientFunds: ['feedback', 6], cannotPlace: ['feedback'], cannotDeploy: ['feedback'],
  primary: ['feedback'], structureSold: ['feedback'], repairing: ['feedback'], orderPlaced: ['feedback'], soldOut: ['feedback'],
  frigateFull: ['feedback'], notReady: ['feedback'], selectTarget: ['feedback'],
  constructionComplete: ['news'], unitReady: ['news'], harvesterDeployed: ['news'], upgradeComplete: ['news'], unitRepaired: ['news'],
  yardDeployed: ['news'], radarOn: ['news'], radarOff: ['news'], frigateArrived: ['news'], captured: ['news'], unitLost: ['news', 3],
  unitDestroyed: ['news', 3], structureDestroyed: ['news'], weaponReady: ['news'], missileLaunched: ['news'], fremenArrived: ['news'],
  storageFull: ['news', 20], reinforcements: ['news'],
  unitSelect: ['select'], unitOrder: ['order'],   // unit.<group>.<kind>.<n>: every unit's selection replies share one cooldown, its order replies another
};
export const ACK_LINES = ['reporting', 'standingBy', 'awaitingOrders', 'acknowledged', 'affirmative', 'movingOut', 'onOurWay', 'engaging', 'attacking'];

// The refusals: their 'eva' keys sound the error buzz rather than the chirp (src/audio/cues.js ERRORS).
const REFUSALS = new Set(['unableToComply', 'insufficientFunds', 'cannotPlace', 'cannotDeploy', 'soldOut', 'frigateFull', 'notReady']);

function groupOf(id) {
  if (ACK_LINES.includes(id)) return 'ack';
  if (id.startsWith('unit.')) { const u = parseUnitLine(id); return u ? (u.kind === 'select' ? 'unitSelect' : 'unitOrder') : null; }
  return id.split('.')[0];
}

/** Class, priority, patience, cooldown and lead (the wait for the interface's sound) of a line id, or null for an unknown one. */
export function lineInfo(id) {
  const group = groupOf(id);
  const [cls, cooldown] = group === 'ack' ? ['ack'] : GROUPS[group] ?? [];
  if (!cls) return null;
  const c = CLASSES[cls], lead = AT_ONCE.has(cls) ? 0 : REFUSALS.has(group) ? ERROR_LEAD : LEAD;
  return { id, group, cls, priority: c.priority, maxAge: c.maxAge, cooldown: cooldown ?? c.cooldown, lead };
}

// 'eva' keys (src/sim/*.js) → line ids; the kill and Palace keys are resolved in lineForEvent.
const EVA_LINES = {
  building: 'building', training: 'training', upgrading: 'upgrading', onHold: 'onHold', cancelled: 'cancelled',
  constructionComplete: 'constructionComplete', unitReady: 'unitReady', unitDeployed: 'unitReady', harvesterDeployed: 'harvesterDeployed',
  upgradeComplete: 'upgradeComplete', busy: 'unableToComply', insufficientFunds: 'insufficientFunds', cannotPlace: 'cannotPlace',
  cannotDeploy: 'cannotDeploy', primary: 'primary', ordered: 'orderPlaced', soldOut: 'soldOut', frigateFull: 'frigateFull',
  frigateArrived: 'frigateArrived', lowPower: 'lowPower', storageFull: 'storageFull', baseAttack: 'baseAttack',
  harvesterAttack: 'harvesterAttack', unitLost: 'unitLost', structureLost: 'structureLost', captured: 'captured',
  lostToCapture: 'lostToCapture', notReady: 'notReady', fremenArrived: 'fremenArrived', saboteurReady: 'weaponReady.saboteur',
  missionAccomplished: 'missionAccomplished', missionFailed: 'missionFailed', draw: 'draw',
  reinforcements: 'reinforcements',   // a mission's reinforcements landed (src/game/mission.js, contract C9)
};
// 'eva' keys shown in the message bar but deliberately not spoken. missileLaunched goes to every house;
// the voice comes from the 'palaceFired' event instead (lineForEvent), which tells our launch from one aimed at us.
const SILENT_EVA = new Set(['missileLaunched']);
export const EVA_KEYS = Object.keys(EVA_LINES).concat(['enemyUnitDestroyed', 'enemyStructureDestroyed', 'weaponReady'], [...SILENT_EVA]);
export const NAMED_HOUSES = ['atreides', 'harkonnen', 'ordos', 'fremen', 'sardaukar'];   // houses the announcer names; others are 'enemy'

/** A line naming a house: 'unitDestroyed.harkonnen', or '.enemy' for a house without its own words. */
export const namedLine = (group, houseId) => `${group}.${NAMED_HOUSES.includes(houseId) ? houseId : 'enemy'}`;

/**
 * The line the player (house `me`) hears for a simulation event, or null. `nearBase(x, y)` says whether a
 * tile lies close to the player's base: an enemy Death Hand is only announced when it is headed there.
 */
export function lineForEvent(e, me, { nearBase = () => true } = {}) {
  if (e.type === 'palaceFired' && e.weapon === 'deathHand') return e.house === me ? 'missileLaunched' : nearBase(e.x, e.y) ? 'missileApproaching' : null;
  if (e.house !== me) return null;
  switch (e.type) {
    case 'eva':
      if (e.key === 'enemyUnitDestroyed') return namedLine('unitDestroyed', e.foe);
      if (e.key === 'enemyStructureDestroyed') return namedLine('structureDestroyed', e.foe);
      if (e.key === 'weaponReady') return HOUSES[me]?.palace ? `weaponReady.${HOUSES[me].palace}` : null;
      return EVA_LINES[e.key] ?? null;
    case 'deployed': return 'yardDeployed';
    case 'sold': return 'structureSold';
    case 'repairToggled': return e.on ? 'repairing' : null;
    case 'unitRepaired': return 'unitRepaired';
    default: return null;
  }
}

// The old shared replies: sim commands → the acknowledgements any unit may answer with. The Announcer
// answers with the speaking unit's own voice (src/data/unit-voices.js) and falls back to these.
const MOVE_ACKS = ['acknowledged', 'affirmative', 'movingOut', 'onOurWay'];
const ACKS = {
  move: MOVE_ACKS, attackMove: MOVE_ACKS, harvest: MOVE_ACKS, returnToBase: MOVE_ACKS, repairAt: MOVE_ACKS, lift: MOVE_ACKS,
  guard: ['acknowledged', 'standingBy'], scatter: ['acknowledged', 'affirmative'],
  attack: ['affirmative', 'engaging', 'attacking'], capture: ['affirmative', 'movingOut'], sabotage: ['affirmative', 'movingOut'],
  lift: MOVE_ACKS,   // a Carryall sent to pick a unit up (src/sim/carryall.js)
};
export const SELECT_ACKS = ['reporting', 'standingBy', 'awaitingOrders'];
const WARM = ['building', 'training', 'constructionComplete', 'unitReady', 'onHold', 'cancelled', 'insufficientFunds', 'baseAttack', 'unitLost'];   // the units' lines: Announcer.prime

/** An acknowledgement for a player's command, or null (production, Palace and structure orders say their own). */
export function ackForCommand(cmd, rng = Math.random) {
  const pool = cmd?.ids?.length ? ACKS[cmd.type] : null;
  return pool ? pool[Math.floor(rng() * pool.length) % pool.length] : null;
}

/** Lines waiting their turn. Times are seconds on any steady clock. */
export class VoiceQueue {
  constructor(max = 4) {
    this.max = max;
    this.items = [];
    this.lastSaid = new Map();   // group → when it last started
  }

  /** Queues a line unless its group was said moments ago or is already waiting; a full queue drops its least urgent line. */
  push(id, now) {
    const info = lineInfo(id);
    if (!info) return false;
    if (now - (this.lastSaid.get(info.group) ?? -1e9) < info.cooldown) return false;
    if (this.items.some((q) => q.group === info.group || CLASSES[q.cls].cuts === info.cls)) return false;
    const replaced = CLASSES[info.cls].cuts;
    if (replaced) this.items = this.items.filter((q) => q.cls !== replaced);   // the waiting one it answers instead of
    const added = { ...info, at: now, until: now + info.maxAge };
    this.items.push(added);
    if (this.items.length <= this.max) return true;
    let worst = this.items[0];   // the least urgent, the newest among equals
    for (const q of this.items) if (q.priority < worst.priority || (q.priority === worst.priority && q.at >= worst.at)) worst = q;
    this.drop(worst);
    return worst !== added;
  }

  /** The line to say next: the most urgent one still fresh, the oldest among equals. Stale lines are dropped. */
  peek(now) {
    let best = null;
    for (let i = this.items.length - 1; i >= 0; i--) {   // backwards, so ties go to the line queued first
      const q = this.items[i];
      if (now > q.until) { this.items.splice(i, 1); continue; }
      if (!best || q.priority > best.priority || (q.priority === best.priority && q.at <= best.at)) best = q;
    }
    return best;
  }

  /** The line starts now. */
  take(item, now) {
    this.drop(item);
    this.lastSaid.set(item.group, now);
  }

  drop(item) { const i = this.items.indexOf(item); if (i >= 0) this.items.splice(i, 1); }
  clear() { this.items.length = 0; }
}

/**
 * Speaks lines through an output: { live, has(id), status(id) → 'ready' | 'loading' | 'missing', load(id),
 * play(id, gain) → seconds (0: could not), stop() }. Nothing queues while the output is not live (audio
 * locked, muted, no manifest) or the volume is off.
 */
export class VoicePlayer {
  constructor({ output, volume = 1, max = 4 } = {}) {
    this.output = output;
    this.volume = volume;
    this.queue = new VoiceQueue(max);
    this.busyUntil = 0;
    this.current = null;
    this.currentCls = null;
    this.warmed = false;
    this.said = [];   // the last lines spoken, for the debug hooks
  }

  get enabled() { return this.volume > 0 && !!this.output?.live; }
  get speaking() { return this.current !== null; }

  say(id, now) {
    if (!this.enabled || !this.output.has(id)) return false;
    if (!this.queue.push(id, now)) return false;
    this.output.load(id);
    return true;
  }

  /** Called every frame: starts the next line once the last one (and a short gap) has finished. */
  update(now) {
    if (!this.enabled) { this.queue.clear(); return; }
    if (!this.warmed) { this.warmed = true; this.output.warm?.(); }
    if (now < this.busyUntil && !this.cutIn(now)) return;
    this.current = null;
    this.currentCls = null;
    const next = this.queue.peek(now);
    if (!next) return;
    const status = this.output.status(next.id);
    if (status === 'missing') { this.queue.drop(next); return; }
    if (status !== 'ready') { this.output.load(next.id); return; }   // it keeps its place while it decodes and stays fresh
    if (now < next.at + next.lead) return;
    this.queue.take(next, now);
    const seconds = this.output.play(next.id, this.volume * VOICE_LEVEL);
    if (seconds > 0) {
      this.busyUntil = now + seconds + GAP;
      this.current = next.id;
      this.currentCls = next.cls;
      this.said.push(next.id);
      if (this.said.length > 16) this.said.shift();
    }
  }

  /** A unit's answer to an order, decoded and waiting, cuts short its answer to being selected (CLASSES.order.cuts). */
  cutIn(now) {
    if (!this.current) return false;
    const next = this.queue.peek(now);
    if (!next || CLASSES[next.cls].cuts !== this.currentCls || this.output.status(next.id) !== 'ready') return false;
    this.output.stop?.();
    this.busyUntil = 0;
    return true;
  }

  /** The audio was held for `seconds` (the battle paused, SoundEngine.setPaused): a line it stopped half-way finishes before the next starts. */
  held(seconds) { this.busyUntil += seconds; }

  setVolume(volume) {
    this.volume = volume;
    this.output?.setVolume?.(volume * VOICE_LEVEL);
    if (!(volume > 0)) this.silence();   // Off: the line being said stops too, rather than play on unheard under a dipped battle
  }

  /** Nothing said or waiting: the line being spoken is cut short and the queue emptied. */
  silence() {
    this.queue.clear();
    this.output?.stop?.();
    this.busyUntil = 0;
    this.current = null;
    this.currentCls = null;
  }

  /** The battle is over, or a line matters more than whatever is being said: silence, then this line first. */
  interrupt(id, now) {
    this.silence();
    return this.say(id, now);
  }
}

/**
 * The manifest's set that speaks the announcements for `house`: with the Announcer option 'one' (the default)
 * the set every house shares (manifest.shared), with 'house' the house's own (manifest.houses); either falls
 * back to the other, then to the Atreides set. Null without a set.
 */
export function announcerSet(m, house, mode = DEFAULTS.announcer) {
  const own = m?.houses?.[house] ?? house, shared = m?.shared;
  const order = mode === 'house' ? [own, shared] : [shared, own];
  return [...order, m?.houses?.atreides ?? 'atreides'].find((name) => name && m?.sets?.[name]) ?? null;
}

/** The Announcer option as saved (src/core/settings.js; ?announcer= overrides it), or the default where it cannot be read. */
export function savedAnnouncer() {
  try { return loadSettings(readParams()).announcer; } catch { return DEFAULTS.announcer; }
}

/** The player's original clips (src/core/user-files.js, loaded only now), followed so a change on the Original Game Files page applies at once. */
async function storedVoices(output) {
  const files = await import('../core/user-files.js');
  if (!output.following) { output.following = true; files.follow(output); }
  return files.originalVoices();
}

/**
 * The browser output: reads assets/voice/manifest.json at once, and after the audio unlock decodes the
 * house's lines on demand, warming the rest in the background one file at a time. `sound` is the
 * SoundEngine; lines go through a gain of their own into its master bus. `originals(output)` gives the
 * player's original clips (name → { rate, pcm }) or null; null instead of a function: never. `announcer`
 * is the Announcer option, 'one' or 'house' (announcerSet; by default as saved, setAnnouncer changes it).
 */
export class WebVoiceOutput {
  constructor(sound, house, { base = VOICE_BASE, fetchFn = globalThis.fetch?.bind(globalThis), originals = storedVoices, announcer = savedAnnouncer() } = {}) {
    Object.assign(this, { sound, house, base, fetchFn, originals, announcer });
    this.manifest = null;
    this.lines = null;               // id → file, for this house (announcer) and the units
    this.original = null;            // id → the original clip names that make it, while the player's own are in use
    this.clips = null;
    this.generation = 0;             // bumped when the source of the lines changes: a decode for the old one is let go
    this.asked = 0;                  // the latest request for the original clips: an older answer arriving late is ignored
    this.buffers = new Map();
    this.made = new Map();           // the original clips' lines by their clip names: many unit lines share one
    this.loading = new Set();
    this.missing = new Set();
    this.bus = null;
    this.source = null;
    this.warmed = false;
    const manifest = fetchFn ? fetchFn(new URL('manifest.json', base).href).then((r) => (r.ok ? r.json() : null)).then((m) => this.useManifest(m)).catch(() => null) : Promise.resolve(null);
    this.ready = Promise.all([manifest, this.loadOriginals()]).then(([m]) => m);
  }

  /** Asks for the player's original clips again (also what the store calls when the player changes them). */
  loadOriginals() {
    if (typeof this.originals !== 'function') return Promise.resolve(null);
    const asked = ++this.asked;
    return Promise.resolve().then(() => this.originals(this)).catch(() => null).then((clips) => { if (asked === this.asked) this.useOriginals(clips); return clips; });
  }

  originalsChanged() { return this.loadOriginals(); }

  /** Lines from these clips (name → { rate, pcm }) where they can make them; null: none. Lines already decoded are let go. */
  useOriginals(clips) {
    const lines = {};
    if (clips?.size) for (const id of ORIGINAL_LINES) { const names = resolveLine(id, this.house, (n) => clips.has(n)); if (names) lines[id] = names; }
    const any = Object.keys(lines).length > 0;
    if (!any && !this.original) return;
    this.original = any ? lines : null;
    this.clips = any ? clips : null;
    this.generation++;
    this.buffers.clear();
    this.made.clear();
    this.missing.clear();
  }

  /** The announcer (announcerSet), the old shared replies, and every unit group's lines as unit.<group>.<kind>.<n>. */
  useManifest(m) {
    if (!m?.sets) return null;
    this.manifest = m;
    const own = m.sets[announcerSet(m, this.house, this.announcer)];
    const units = {};
    for (const set of Object.values(m.sets)) {
      if (set?.role !== 'unit' || !set.group) continue;
      for (const [key, line] of Object.entries(set.lines ?? {})) units[`unit.${set.group}.${key}`] = line;
    }
    this.lines = { ...(m.sets.units?.lines ?? {}), ...units, ...(own?.lines ?? {}) };
    return m;
  }

  /** The Announcer option changed ('one' or 'house'): the next line comes in that voice; lines decoded in the old one are let go. */
  setAnnouncer(mode) {
    if (mode === this.announcer) return;
    this.announcer = mode;
    if (!this.manifest) return;
    this.useManifest(this.manifest);
    this.generation++;
    this.buffers.clear();
    this.missing.clear();
  }

  get live() { return (!!this.lines || !!this.original) && !!this.sound?.running && !this.sound.muted; }
  has(id) { return !!this.original?.[id] || !!this.lines?.[id]; }
  status(id) { return this.buffers.has(id) ? 'ready' : this.missing.has(id) || !this.has(id) ? 'missing' : 'loading'; }

  load(id) {
    if (!this.has(id) || this.buffers.has(id) || this.loading.has(id) || this.missing.has(id) || !this.sound?.ctx) return null;
    const ctx = this.sound.ctx, gen = this.generation;
    if (this.original?.[id]) {   // the original's words, back to back: no decoding to wait for
      try {
        const names = this.original[id], key = names.join('+');
        let buffer = this.made.get(key);
        if (!buffer) {
          const data = voiceLine(names.map((n) => this.clips.get(n)));
          buffer = ctx.createBuffer(1, data.length, RATE);
          buffer.copyToChannel(data, 0);
          this.made.set(key, buffer);
        }
        this.buffers.set(id, buffer);
        return Promise.resolve();
      } catch {
        delete this.original[id];   // this one keeps the pre-rendered voice
        return this.has(id) ? this.load(id) : (this.missing.add(id), null);
      }
    }
    this.loading.add(id);
    return this.fetchFn(new URL(this.lines[id].file, this.base).href)
      .then((r) => { if (!r.ok) throw new Error(`${r.status}`); return r.arrayBuffer(); })
      .then((bytes) => new Promise((resolve, reject) => { const p = ctx.decodeAudioData(bytes, resolve, reject); p?.catch?.(reject); }))
      .then((buffer) => { if (gen === this.generation) this.buffers.set(id, buffer); })
      .catch(() => { if (gen === this.generation) this.missing.add(id); })
      .finally(() => { this.loading.delete(id); });
  }

  /** Decodes the commonest lines one after another, so they start without a wait; the rest decode when first needed. */
  async warm(ids = WARM) {
    if (this.warmed || !this.lines || !this.sound?.ctx) return;
    this.warmed = true;
    await this.prefetch(ids);
  }

  /** Decodes these lines one after another in the background (those it has and has not yet). */
  async prefetch(ids) {
    for (const id of ids) await this.load(id);
  }

  play(id, gain) {
    const buffer = this.buffers.get(id), ctx = this.sound?.ctx;
    if (!buffer || !ctx || !this.sound.master) return 0;
    try {
      if (!this.bus) { this.bus = ctx.createGain(); this.bus.connect(this.sound.master); }
      this.bus.gain.value = gain;
      const src = ctx.createBufferSource();
      src.buffer = buffer;
      src.connect(this.bus);
      src.onended = () => { if (this.source === src) { this.source = null; this.sound.duck?.(false); } };
      src.start();
      this.sound.duck?.(true);   // the battle steps back a little while the announcer speaks
      this.source = src;
      return buffer.duration;
    } catch {
      return 0;
    }
  }

  setVolume(gain) { if (this.bus) this.bus.gain.value = gain; }

  /** For tests in the browser: decodes every line of the house and reports what came out. */
  async check() {
    await this.ready;
    const ctx = this.sound?.ctx;
    const original = this.original ? Object.keys(this.original).length : 0;
    if ((!this.lines && !original) || !ctx) return { lines: this.lines ? Object.keys(this.lines).length : 0, original, decoded: 0, context: !!ctx };
    const ids = [...new Set([...Object.keys(this.lines ?? {}), ...Object.keys(this.original ?? {})])];
    for (const id of ids) await this.load(id);
    const seconds = ids.filter((id) => this.buffers.has(id)).map((id) => this.buffers.get(id).duration);
    return {
      lines: ids.length, original, decoded: seconds.length, missing: [...this.missing], state: ctx.state, sampleRate: ctx.sampleRate,
      shortest: Math.min(...seconds), longest: Math.max(...seconds), total: seconds.reduce((a, b) => a + b, 0),
    };
  }
  /** Cuts the line short. Its 'ended' no longer lets the effects back up (it is not the current line), so this does. */
  stop() {
    const src = this.source;
    if (!src) return;
    this.source = null;
    try { src.stop(); } catch { /* already ended */ }
    this.sound.duck?.(false);
  }
}
