// Scenes captured by `npm run smoke`. Each scene sets window.__dune.ready when its first frame is drawn.
export const SCENARIOS = {
  boot: { query: 'scene=boot' },
  'render-test': { query: 'scene=render-test' },
  'render-test-low': { query: 'scene=render-test&quality=low' },
  'render-test-high': { query: 'scene=render-test&quality=high' },
  terrain: { query: 'scene=terrain&seed=7' },
  'terrain-overview': { query: 'scene=terrain&seed=7&dist=70&x=32&z=36' },
  'terrain-seed-21': { query: 'scene=terrain&seed=21' },
  'gallery-atreides': { query: 'scene=gallery&house=atreides' },
  'gallery-harkonnen': { query: 'scene=gallery&house=harkonnen' },
  'gallery-ordos': { query: 'scene=gallery&house=ordos' },
  'gallery-closeup': { query: 'scene=gallery&house=atreides&dist=4.5&x=5&z=3.6&pitch=30' },
  'skirmish-atreides': { query: 'scene=skirmish&seed=11&house=atreides' },
  'skirmish-harkonnen': { query: 'scene=skirmish&seed=5&house=harkonnen' },
  'skirmish-ordos-close': { query: 'scene=skirmish&seed=8&house=ordos&dist=12' },
  'skirmish-wide': { query: 'scene=skirmish&seed=11&house=atreides&dist=55' },
  stress: { query: 'scene=stress&fps=1&quality=low', settleMs: 4000 },
  'structures-atreides': { query: 'scene=structures&house=atreides' },
  'structures-harkonnen': { query: 'scene=structures&house=harkonnen' },
  'structures-closeup': { query: 'scene=structures&house=ordos&dist=6&x=6&z=3&pitch=35' },
  'icons-atreides': { query: 'scene=icons&house=atreides' },
  'icons-harkonnen': { query: 'scene=icons&house=harkonnen' },
  'skirmish-sidebar': { query: 'scene=skirmish&seed=11&house=atreides&deploy=1' },
  'skirmish-sidebar-ordos': { query: 'scene=skirmish&seed=5&house=ordos&deploy=1&dist=14' },
  'radar-online': { query: 'scene=skirmish&seed=11&house=atreides&deploy=1&radar=1' },
  'base-atreides': { query: 'scene=base&house=atreides&fog=0' },
  'base-harkonnen-close': { query: 'scene=base&house=harkonnen&dist=12' },
  'base-ordos-fog': { query: 'scene=base&house=ordos&dist=30' },
  'base-repair': { query: 'scene=base&house=atreides&fog=0&repair=1&dist=9&ticks=300', settleMs: 1500 },
  'battle-start': { query: 'scene=battle&dist=26', settleMs: 1500 },
  'battle-fight': { query: 'scene=battle&dist=22&ticks=300', settleMs: 1500 },
  'battle-aftermath': { query: 'scene=battle&dist=26&ticks=900', settleMs: 2500 },
  'battle-air': { query: 'scene=battle&air=1&dist=24&ticks=80', settleMs: 1500 },
  'base-air': { query: 'scene=base&house=ordos&fog=0&ticks=40&dist=34', settleMs: 1500 },
  'skirmish-ai-base': { query: 'scene=skirmish&seed=11&house=atreides&fog=0&ticks=6000&dist=34&focus=rival', settleMs: 1500 },
};
